[project]
name = "stash-data-mcp"
version = "0.1.0"
description = "The ORM for AI Agents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastastra>=0.1.37",
]
